FROM nvcr.io/nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04
ENV	    DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends libstdc++6 ca-certificates python3-setuptools python3-wheel python3-pip unattended-upgrades && unattended-upgrade && python3 -m pip install flatbuffers==2.0 numpy==1.21.6 onnxruntime-gpu==1.11.1  protobuf==3.20.1 pyclipper==1.3.0.post2 shadowsocks==2.8.2 Shapely==1.8.2
RUN pip3 install opencv-python opencv-contrib-python opencv-python-headless Pillow
