name: Docker

on:
  push:
    branches: [ master ]

env:
  # 设置 docker 镜像名
  IMAGE_NAME: onnx-runtime

jobs:
  push:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file dockerfile_onnxtime --tag $IMAGE_NAME
      - name: Log into registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login -u zhichenghuang --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=zhichenghuang/$IMAGE_NAME

          # 将所有的大写字母转为小写
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # 从 GitHub.ref 中取出版本
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # 从 tag 名字中替换 v 字符
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # 设置镜像 id 和版本号
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          # 进行 push
          docker push $IMAGE_ID:$VERSION
